
#
# registry keys for windows10
#

# disable auto admin logon

- name: disable auto admin logon
  win_regedit: 
    path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon
    name: AutoAdminLogon
    data: 0
    type: dword
    state: present
  when: win10_autologon is defined and win10_autologon == true

# enable firewall for domain, public and private profiles

- name: enable firewall for domain, public and private profiles
  win_firewall:
    state: enabled
    profiles:
    - Domain
    - Private
    - Public
  when: win10_firewall is defined and win10_firewall == true

# enable firewall rule to allow icmp v4 (ping) 

- name: enable firewall rule to allow icmp v4 (ping)
  win_firewall_rule:
    name: ICMP Allow incoming V4 echo request
    direction: in
    protocol: icmpv4
    profiles: domain
    action: allow
    state: present
    enabled: yes
  when: win10_firewall is defined and win10_firewall == true

# enable remote desktop services

- name: enable remote desktop services
  win_regedit: 
    path: HKLM:\SYSTEM\CurrentControlSet\Control\Terminal Server
    name: fDenyTSConnections
    data: 0
    type: dword
    state: present
  when: win10_rdp is defined and win10_rdp == true

- name: enable firewall rule to allow rdp
  win_firewall_rule:
    name: Remote Desktop
    direction: in
    localport: 3389
    protocol: tcp
    profiles: domain
    action: allow
    state: present
    enabled: yes
  when: win10_rdp is defined and win10_rdp == true

# enable shutdown privilege from logon screen

- name: enable shutdown privilege from logon screen
  win_regedit: 
    path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System
    name: shutdownwithoutlogon
    data: 1
    type: dword
    state: present
  when: win10_logonscreen_privilege is defined and win10_logonscreen_privilege == true

# enable reboot, switch account and signout privilege from start menu 

- name: enable reboot privilege from start menu
  win_regedit: 
    path: HKLM:\SOFTWARE\Microsoft\PolicyManager\default\Start\HideRestart
    name: value
    data: 0
    type: dword
    state: present
  when: win10_startmenu_privilege is defined and win10_startmenu_privilege == true

- name: enable switch account privilege from start menu
  win_regedit: 
    path: HKLM:\SOFTWARE\Microsoft\PolicyManager\default\Start\HideSwitchAccount
    name: value
    data: 0
    type: dword
    state: present
  when: win10_startmenu_privilege is defined and win10_startmenu_privilege == true

- name: enable signout privilege from start menu
  win_regedit: 
    path: HKLM:\SOFTWARE\Microsoft\PolicyManager\default\Start\HideSignOut
    name: value
    data: 0
    type: dword
    state: present
  when: win10_startmenu_privilege is defined and win10_startmenu_privilege == true

# disable shutdown, sleep and hibernate privilege from start menu 

- name: disable shutdown privilege from start menu
  win_regedit: 
    path: HKLM:\SOFTWARE\Microsoft\PolicyManager\default\Start\HideShutDown
    name: value
    data: 1
    type: dword
    state: present
  when: win10_startmenu_privilege is defined and win10_startmenu_privilege == true

- name: disable sleep privilege from start menu 
  win_regedit: 
    path: HKLM:\SOFTWARE\Microsoft\PolicyManager\default\Start\HideSleep
    name: value
    data: 1
    type: dword
    state: present
  when: win10_startmenu_privilege is defined and win10_startmenu_privilege == true

- name: disable hibernate privilege from start menu 
  win_regedit: 
    path: HKLM:\SOFTWARE\Microsoft\PolicyManager\default\Start\HideHibernate
    name: value
    data: 1
    type: dword
    state: present
  when: win10_startmenu_privilege is defined and win10_startmenu_privilege == true

# disable automatic windows updates

- name: disable automatic windows updates
  win_regedit: 
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate\AU
    name: NoAutoUpdate
    data: 1
    type: dword
    state: present
  when: win10_auto_update is defined and win10_auto_update == true

# stop windows update restarting pc

- name: stop windows update restarting pc 
  win_regedit: 
    path: HKLM:\Software\Policies\Microsoft\Windows\WindowsUpdate\AU
    name: NoAutoRebootWithLoggedOnUsers
    data: 1
    type: dword
    state: present
  when: win10_auto_reboot is defined and win10_auto_reboot == true

# disable thumbsdb on network drives

- name: disable thumbsdb on network drives 
  win_regedit: 
    path: HKCU:\Software\Policies\Microsoft\Windows\Explorer 
    name: DisableThumbsDBOnNetworkFolders
    data: 1
    type: dword
    state: present
  when: win10_thumbs_db is defined and win10_thumbs_db == true

# disable windows feedback

- name: disable windows feedback 
  win_regedit: 
    path: HKCU:\Software\Microsoft\Siuf\Rules 
    name: NumberOfSIUFInPeriod
    data: 0
    type: dword
    state: present
  when: win10_windows_feedback is defined and win10_windows_feedback == true

- name: disable windows feedback
  win_regedit: 
    path: HKCU:\Software\Microsoft\Siuf\Rules 
    name: PeriodInNanoSeconds
    data: 0
    type: dword
    state: present
  when: win10_windows_feedback is defined and win10_windows_feedback == true

# enable windows explorer statusbar

- name: enable windows explorer statusbar 
  win_regedit: 
    path: HKCU:\Software\Microsoft\Internet Explorer\Main 
    name: Show_StatusBar
    data: yes
    type: string
    state: present
  when: win10_explorer_statusbar is defined and win10_explorer_statusbar == true

- name: enable windows explorer statusbar 
  win_regedit: 
    path: HKCU:\Software\Microsoft\Internet Explorer\Main 
    name: StatusBarOther
    data: 1
    type: dword
    state: present
  when: win10_explorer_statusbar is defined and win10_explorer_statusbar == true

# remove windows store taskbar

- name: remove windows store taskbar
  win_regedit: 
    path: HKCU:\Software\Policies\Microsoft\Windows\Explorer 
    name: NoPinningStoreToTaskbar
    data: 1
    type: dword
    state: present
  when: win10_store_taskbar is defined and win10_store_taskbar == true

- name: remove windows store taskbar
  win_regedit: 
    path: HKLM:\Software\Policies\Microsoft\Windows\Explorer 
    name: NoPinningStoreToTaskbar
    data: 1
    type: dword
    state: present
  when: win10_store_taskbar is defined and win10_store_taskbar == true

# keep numlock always on

# - name: keep numlock always on 
#   win_regedit: 
#     path: HKU:\Control Panel\Keyboard
#     name: InitialKeyboardIndicators
#     data: 2
#     type: dword # or binary
#     state: present
#   when: win10_numlock is defined and win10_numlock == true

# disable microsoft onedrive

- name: disable microsoft onedrive 
  win_regedit: 
    path: HKLM:\Software\Policies\Microsoft\Windows\OneDrive
    name: DisableFileSyncNGSC
    data: 1
    type: dword
    state: present
  when: win10_onedrive is defined and win10_onedrive == true

# confirm file deletion

- name: confirm file deletion 
  win_regedit: 
    path: HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\Explorer
    name: ConfirmFileDelete
    data: 1
    type: dword
    state: present
  when: win10_file_deletion is defined and win10_file_deletion == true

# disable online tips and help for settings app

- name: disable online tips and help for settings app
  win_regedit: 
    path: HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\Explorer
    name: AllowOnlineTips
    data: 0
    type: dword
    state: present
  when: win10_online_tips is defined and win10_online_tips == true

# disable activity history

- name: disable activity history 
  win_regedit: 
    path: HKLM:\Software\Policies\Microsoft\Windows\System
    name: PublishUserActivities
    data: 0
    type: dword
    state: present
  when: win10_activity_history is defined and win10_activity_history == true

# hide microsoft edge button in internet explorer

- name: hide microsoft edge button in internet explorer
  win_regedit: 
    path: HKCU:\Software\Policies\Microsoft\Internet Explorer\Main 
    name: HideNewEdgeButton
    data: 1
    type: dword
    state: present
  when: win10_edge_button is defined and win10_edge_button == true

# disable microsoft telemetry 

- name: disable microsoft telemetry 
  win_regedit: 
    path: HKLM:\Software\Policies\Microsoft\MRT
    name: DontOfferThroughWUAU
    data: 1
    type: dword
    state: present
  when: win10_telemetry is defined and win10_telemetry == true

- name: disable microsoft telemetry 
  win_regedit: 
    path: HKLM:\Software\Policies\Microsoft\MRT
    name: DontReportInfectionInformation
    data: 1
    type: dword
    state: present
  when: win10_telemetry is defined and win10_telemetry == true

# disable windows error reporting current user

- name: disable windows error reporting current user 
  win_regedit: 
    path: HKCU:\Software\Microsoft\Windows\Windows Error Reporting 
    name: Disabled
    data: 1
    type: dword
    state: present
  when: win10_error_reporting is defined and win10_error_reporting == true

# disable microsoft windows store

- name: disable microsoft windows store 
  win_regedit: 
    path: HKLM:\Software\Microsoft\WindowsStore
    name: RemoveWindowsStore
    data: 1
    type: dword
    state: present
  when: win10_windows_store is defined and win10_windows_store == true

# switch off advertising ads in start menu

- name: disable advertising ads in start menu
  win_regedit: 
    path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced 
    name: ShowSyncProviderNotification
    data: 0
    type: dword
    state: present
  when: win10_startmenu_ads is defined and win10_startmenu_ads == true

# disable ads in file explorer

- name: disable ads in file explorer 
  win_regedit: 
    path: HKLM:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced
    name: ShowSyncProviderNotifications
    data: 0
    type: dword
    state: present
  when: win10_explorer_ads is defined and win10_explorer_ads == true

# disable app launch tracking

- name: disable app launch tracking
  win_regedit: 
    path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced 
    name: Start_TrackProgs
    data: 0
    type: dword
    state: present
  when: win10_app_tracking is defined and win10_app_tracking == true

# change the logon screen to a solid color

- name: disable logon background image 
  win_regedit: 
    path: HKLM:\Software\Policies\Microsoft\Windows\System
    name: DisableLogonBackgroundImage
    data: 1
    type: dword
    state: present
  when: win10_logon_background is defined and win10_logon_background == true

# set cortana searchbox taskbar icon mode

- name: set cortana searchbox taskbar icon mode
  win_regedit: 
    path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Search
    name: SearchboxTaskbarMode
    data: 1
    type: dword
    state: present
  when: win10_cortana is defined and win10_cortana == true

# disable cortana but keep search

- name: disable cortana but keep search - PreventIndexOnBattery
  win_regedit: 
    path: HKLM:\Software\Policies\Microsoft\Windows\Windows Search
    name: PreventIndexOnBattery
    data: 1
    type: dword
    state: present
  when: win10_cortana is defined and win10_cortana == true 

- name: disable cortana but keep search - AllowSearchToUseLocation
  win_regedit: 
    path: HKLM:\Software\Policies\Microsoft\Windows\Windows Search
    name: AllowSearchToUseLocation
    data: 0
    type: dword
    state: present
  when: win10_cortana is defined and win10_cortana == true 

- name: disable cortana but keep search - AllowCortana
  win_regedit: 
    path: HKLM:\Software\Policies\Microsoft\Windows\Windows Search
    name: AllowCortana
    data: 0
    type: dword
    state: present
  when: win10_cortana is defined and win10_cortana == true 

- name: disable cortana but keep search - ConnectedSearchUseWeb
  win_regedit: 
    path: HKLM:\Software\Policies\Microsoft\Windows\Windows Search
    name: ConnectedSearchUseWeb
    data: 0
    type: dword
    state: present
  when: win10_cortana is defined and win10_cortana == true 

- name: disable cortana but keep search - DisableWebSearch
  win_regedit: 
    path: HKLM:\Software\Policies\Microsoft\Windows\Windows Search
    name: DisableWebSearch
    data: 1
    type: dword
    state: present
  when: win10_cortana is defined and win10_cortana == true 

- name: disable cortana but keep search - PreventIndexingOutlook
  win_regedit: 
    path: HKLM:\Software\Policies\Microsoft\Windows\Windows Search
    name: PreventIndexingOutlook
    data: 1
    type: dword
    state: present
  when: win10_cortana is defined and win10_cortana == true 

- name: disable cortana but keep search - PreventIndexingEmailAttachments
  win_regedit: 
    path: HKLM:\Software\Policies\Microsoft\Windows\Windows Search
    name: PreventIndexingEmailAttachments
    data: 1
    type: dword
    state: present
  when: win10_cortana is defined and win10_cortana == true 

- name: disable cortana but keep search - ConnectedSearchPrivacy
  win_regedit: 
    path: HKLM:\Software\Policies\Microsoft\Windows\Windows Search
    name: ConnectedSearchPrivacy
    data: 3
    type: dword
    state: present
  when: win10_cortana is defined and win10_cortana == true 

- name: disable cortana but keep search - ConnectedSearchSafeSearch 
  win_regedit: 
    path: HKLM:\Software\Policies\Microsoft\Windows\Windows Search
    name: ConnectedSearchSafeSearch
    data: 3
    type: dword
    state: present
  when: win10_cortana is defined and win10_cortana == true 

- name: disable cortana but keep search - ConnectedSearchUseWebOverMeteredConnections
  win_regedit: 
    path: HKLM:\Software\Policies\Microsoft\Windows\Windows Search
    name: ConnectedSearchUseWebOverMeteredConnections
    data: 0
    type: dword
    state: present
  when: win10_cortana is defined and win10_cortana == true 

- name: disable cortana but keep search - PreventRemoteQueries
  win_regedit: 
    path: HKLM:\Software\Policies\Microsoft\Windows\Windows Search
    name: PreventRemoteQueries
    data: 1
    type: dword
    state: present
  when: win10_cortana is defined and win10_cortana == true 

- name: disable cortana but keep search - DisableRemovableDriveIndexing
  win_regedit: 
    path: HKLM:\Software\Policies\Microsoft\Windows\Windows Search
    name: DisableRemovableDriveIndexing
    data: 1
    type: dword
    state: present
  when: win10_cortana is defined and win10_cortana == true 

- name: disable cortana but keep search - ConnectedSearchUseWeb
  win_regedit: 
    path: HKLM:\Software\Policies\Microsoft\Windows\Windows Search
    name: ConnectedSearchUseWeb
    data: 0
    type: dword
    state: present
  when: win10_cortana is defined and win10_cortana == true 

- name: disable cortana but keep search - BingSearchEnabled
  win_regedit: 
    path: HKLM:\Software\Policies\Microsoft\Windows\Windows Search
    name: BingSearchEnabled
    data: 0
    type: dword
    state: present
  when: win10_cortana is defined and win10_cortana == true 

- name: disable cortana but keep search - CortanaConsent
  win_regedit: 
    path: HKLM:\Software\Policies\Microsoft\Windows\Windows Search
    name: CortanaConsent
    data: 0
    type: dword
    state: present
  when: win10_cortana is defined and win10_cortana == true 

- name: disable cortana but keep search - AllowSearchToUseLocation
  win_regedit: 
    path: HKLM:\Software\Policies\Microsoft\Windows\Windows Search
    name: AllowSearchToUseLocation
    data: 0
    type: dword
    state: present
  when: win10_cortana is defined and win10_cortana == true 

- name: disable cortana but keep search - AllowCloudSearch 
  win_regedit: 
    path: HKLM:\Software\Policies\Microsoft\Windows\Windows Search
    name: AllowCloudSearch
    data: 0
    type: dword
    state: present
  when: win10_cortana is defined and win10_cortana == true 

# make sure windows management framework and powershell is latest version 

- name: make sure windows management framework and powershell is latest version
  win_chocolatey:
     name: powershell
     state: latest
  register: check_powershell5
  become: yes
  become_method: runas
  when: win10_powershell is defined and win10_powershell == true

- name: reboot to complete powershell 5.0 install
  win_reboot:
    shutdown_timeout: 600
    reboot_timeout: 600
    post_reboot_delay: 120
  when: check_powershell5.changed
  when: win10_powershell is defined and win10_powershell == true

