---
- win_shell: |
    $computer = gc env:computername
    $key = "{{win10_activation_key}}"
    $service = get-wmiObject -query "select * from SoftwareLicensingService" -computername $computer
    $service.InstallProductKey($key)
    $service.RefreshLicenseStatus()
